// Mocks generated by Mockito 5.4.4 from annotations
// in todo/test/todo/presentation/bloc/task_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo/core/errors/failure.dart' as _i6;
import 'package:todo/feature/todo_list/domain/entities/task.dart' as _i7;
import 'package:todo/feature/todo_list/domain/repositories/task_repository.dart'
    as _i2;
import 'package:todo/feature/todo_list/domain/usecases/add_task_uc.dart' as _i8;
import 'package:todo/feature/todo_list/domain/usecases/delete_task.dart'
    as _i10;
import 'package:todo/feature/todo_list/domain/usecases/edit_task_uc.dart'
    as _i9;
import 'package:todo/feature/todo_list/domain/usecases/get_filtered_task.dart'
    as _i4;
import 'package:todo/feature/todo_list/domain/usecases/update_task_status.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskRepository_0 extends _i1.SmartFake
    implements _i2.TaskRepository {
  _FakeTaskRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFilteredTasks].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFilteredTasks extends _i1.Mock implements _i4.GetFilteredTasks {
  MockGetFilteredTasks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTaskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TaskRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tasks>>> call(
          _i4.FilterParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tasks>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Tasks>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tasks>>>);
}

/// A class which mocks [AddTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTask extends _i1.Mock implements _i8.AddTask {
  MockAddTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTaskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TaskRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i7.Tasks? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [task],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [task],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [EditTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditTask extends _i1.Mock implements _i9.EditTask {
  MockEditTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTaskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TaskRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i7.Tasks? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [task],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [task],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [DeleteTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTask extends _i1.Mock implements _i10.DeleteTask {
  MockDeleteTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTaskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TaskRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [UpdateTaskStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTaskStatus extends _i1.Mock implements _i11.UpdateTaskStatus {
  MockUpdateTaskStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTaskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TaskRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i7.Tasks? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [task],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [task],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
